/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Surfaces
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'surface-tint': '#ba1724',
        // On-surface
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#5b403e',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        // Outline
        outline: '#8f6f6d',
        'outline-variant': '#e4beba',
        // Primary
        primary: '#b71422',
        'on-primary': '#ffffff',
        'primary-container': '#db3237',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb3ae',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3ae',
        'on-primary-fixed': '#410004',
        'on-primary-fixed-variant': '#930014',
        // Secondary
        secondary: '#845400',
        'on-secondary': '#ffffff',
        'secondary-container': '#feb246',
        'on-secondary-container': '#6f4600',
        'secondary-fixed': '#ffddb6',
        'secondary-fixed-dim': '#ffb95a',
        'on-secondary-fixed': '#2a1800',
        'on-secondary-fixed-variant': '#643f00',
        // Tertiary
        tertiary: '#005bb3',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1a73da',
        'on-tertiary-container': '#fefcff',
        'tertiary-fixed': '#d6e3ff',
        'tertiary-fixed-dim': '#a9c7ff',
        'on-tertiary-fixed': '#001b3e',
        'on-tertiary-fixed-variant': '#00468c',
        // Error
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        // Background
        background: '#fcf9f8',
        'on-background': '#1c1b1b',
      },
      fontFamily: {
        sans: ['PlusJakartaSans_400Regular', 'sans-serif'],
        'sans-medium': ['PlusJakartaSans_500Medium', 'sans-serif'],
        'sans-semibold': ['PlusJakartaSans_600SemiBold', 'sans-serif'],
        'sans-bold': ['PlusJakartaSans_700Bold', 'sans-serif'],
        'sans-extrabold': ['PlusJakartaSans_800ExtraBold', 'sans-serif'],
        display: ['PlaywriteNO', 'serif'],
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px' }],
        'headline-lg': ['28px', { lineHeight: '36px' }],
        'headline-md': ['22px', { lineHeight: '28px' }],
        'body-lg': ['18px', { lineHeight: '26px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label-md': ['12px', { lineHeight: '16px' }],
        button: ['16px', { lineHeight: '20px' }],
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        margin: '20px',
      },
      boxShadow: {
        card: '0 2px 12px 0 rgba(183, 20, 34, 0.04), 0 1px 3px 0 rgba(0,0,0,0.06)',
        fab: '0 4px 24px 0 rgba(183, 20, 34, 0.14), 0 2px 6px 0 rgba(0,0,0,0.10)',
      },
    },
  },
  plugins: [],
};
